query GetSingleCollection($collectionId: ID!) {
  collection(id: $collectionId) {
    id
    handle
    title
    description
    image {
      id
      url
      altText
      width
      height
    }
    products(first: 50) {
      nodes {
        id
        title
        productType
        handle
        vendor
        options(first: 10) {
          id
          name
          optionValues {
            id
            name
            swatch {
              color
              image {
                id
                alt
                previewImage {
                  altText
                  id
                  width
                  height
                  url
                }
              }
            }
          }
          values
        }
        variants(first: 10) {
          nodes {
            id
            title
            price {
              amount
              currencyCode
            }
            availableForSale
            quantityAvailable
            currentlyNotInStock
            quantityRule {
              increment
              maximum
              minimum
            }
          }
        }
        images(first: 5) {
          nodes {
            id
            url
            altText
            width
            height
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
