mutation CartLinesAdd($cartId: ID!, $lines: [CartLineInput!]!) {
  cartLinesAdd(cartId: $cartId, lines: $lines) {
    cart {
      id
      checkoutUrl
      totalQuantity
      lines(first: 50) {
        nodes {
          id
          quantity
          attributes {
            key
            value
          }
          merchandise {
            ... on ProductVariant {
              id
              title
              sku
              availableForSale
              currentlyNotInStock
              image {
                id
                altText
                height
                thumbhash
                url
              }
              product {
                id
                title
                handle
                availableForSale
                productType
                images(first: 5) {
                  nodes {
                    id
                    altText
                    height
                    thumbhash
                    url
                  }
                }
                category {
                  id
                  name
                }
              }
              price {
                amount
                currencyCode
              }
            }
          }
          cost {
            amountPerQuantity {
              amount
              currencyCode
            }
            totalAmount {
              amount
              currencyCode
            }
          }
        }
      }
      cost {
        subtotalAmount {
          amount
          currencyCode
        }
        totalAmount {
          amount
          currencyCode
        }
        totalTaxAmount {
          amount
          currencyCode
        }
      }
    }
    userErrors {
      field
      message
    }
    # warnings {
    #   # CartWarning fields
    # }
  }
}
