query GetCart($cartId: ID!) {
  cart(id: $cartId) {
    id
    checkoutUrl
    totalQuantity
    lines(first: 50) {
      nodes {
        id
        quantity
        attributes {
          key
          value
        }
        merchandise {
          ... on ProductVariant {
            id
            title
            sku
            availableForSale
            currentlyNotInStock
            image {
              id
              altText
              height
              thumbhash
              url
            }
            product {
              id
              title
              handle
              availableForSale
              productType
              images(first: 5) {
                nodes {
                  id
                  altText
                  height
                  thumbhash
                  url
                }
              }
              category {
                id
                name
              }
            }
            price {
              amount
              currencyCode
            }
          }
        }
        cost {
          amountPerQuantity {
            amount
            currencyCode
          }
          totalAmount {
            amount
            currencyCode
          }
        }
      }
    }
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
      totalAmount {
        amount
        currencyCode
      }
      totalTaxAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      email
      phone
      countryCode
      customer {
        id
        email
        firstName
        lastName
      }
    }
    delivery {
      addresses {
        id
        selected
        oneTimeUse
        address {
          ... on CartDeliveryAddress {
            firstName
            lastName
            company
            address1
            address2
            city
            provinceCode
            zip
            countryCode
          }
        }
      }
    }
  }
}
