query GetCart($cartId: ID!) {
  cart(id: $cartId) {
    id
    checkoutUrl
    lines(first: 50) {
      edges {
        node {
          id
          quantity
          merchandise {
            ... on ProductVariant {
              id
              title
              sku
              availableForSale
              currentlyNotInStock
              image {
                id
                altText
                height
                thumbhash
                url
              }
              product {
                id
                title
                type
                handle
                availableForSale
                images(first: 5) {
                  nodes {
                    id
                    altText
                    height
                    thumbhash
                    url
                  }
                }
                category {
                  id
                  name
                }
              }
              price {
                amount
                currencyCode
              }
            }
          }
          cost {
            amountPerQuantity {
              amount
              currencyCode
            }
            totalAmount {
              amount
              currencyCode
            }
          }
        }
      }
    }
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
      totalAmount {
        amount
        currencyCode
      }
      totalTaxAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      email
      phone
      countryCode
      customer {
        id
        email
        firstName
        lastName
      }
    }
    delivery {
      addresses {
        id
        selected
        oneTimeUse
        address {
          ... on CartDeliveryAddress {
            firstName
            lastName
            company
            address1
            address2
            city
            provinceCode
            zip
            countryCode
          }
        }
      }
    }
  }
}
