export const PRODUCTS = [
  {
    name: ["Velvet Amber Skin", "EAU De Perfume"],
    image: "/assets/images/products/perfume-bottle-1.avif",
    description: "Perfume Bottle 1",
    flavor: "Ambery Floral",
    price: 100,
    model: "",
  },
  {
    name: ["Velvet Amber Sun", "EAU De Perfume"],
    image: "/assets/images/products/perfume-bottle-2.avif",
    description: "Perfume Bottle 2",
    flavor: "Amber Vanilla",
    price: 100,
    model: "",
  },
  {
    name: ["Velvet Black", "Patchouli"],
    image: "/assets/images/products/perfume-bottle-3.avif",
    description: "Perfume Bottle 3",
    flavor: "Chypre Leather",
    price: 100,
    model: "",
  },
  {
    name: ["Velvet Blue Mask", "EAU De Perfume"],
    image: "/assets/images/products/perfume-bottle-4.avif",
    description: "Perfume Bottle 4",
    flavor: "Woody Musky",
    price: 100,
    model: "",
  },
  {
    name: ["Velvet Desert OUD", "EAU De Perfume"],
    image: "/assets/images/products/perfume-bottle-5.avif",
    description: "Perfume Bottle 5",
    flavor: "Leather OUD",
    price: 100,
    model: "",
  },
  {
    name: ["Velvet Desire", "EAU De Perfume"],
    image: "/assets/images/products/perfume-bottle-6.avif",
    description: "Perfume Bottle 6",
    flavor: "Floral White Flower",
    price: 100,
    model: "",
  },
  {
    name: ["Velvet Exotic Leather", "EAU De Perfume"],
    image: "/assets/images/products/perfume-bottle-7.avif",
    description: "Perfume Bottle 7",
    flavor: "Ambery Aromatic",
    price: 100,
    model: "",
  },
];
