mutation customerAddressCreate(
  $customerAccessToken: String!
  $address: MailingAddressInput!
) {
  customerAddressCreate(
    customerAccessToken: $customerAccessToken
    address: $address
  ) {
    customerAddress {
      id
      firstName
      lastName
      address1
      address2
      city
      country
      countryCode
      formatted
      latitude
      longitude
      phone
      province
      provinceCode
      zip
    }
    customerUserErrors {
      code
      message
      field
    }
  }
}
