query GetCustomer($customerAccessToken: String!) {
  customer(customerAccessToken: $customerAccessToken) {
    id
    firstName
    lastName
    displayName
    acceptsMarketing
    email
    phone
    updatedAt
    createdAt
    numberOfOrders
    addresses(first: 10) {
      nodes {
        id
        firstName
        lastName
        address1
        address2
        city
        country
        countryCode
        formatted
        formattedArea
        latitude
        longitude
        phone
        company
        province
        provinceCode
        zip
      }
    }
    defaultAddress {
      id
      firstName
      lastName
      address1
      address2
      city
      country
      company
      countryCode
      formatted
      formattedArea
      latitude
      longitude
      phone
      province
      provinceCode
      zip
    }
  }
}
