# Resets a customer’s password with the token received from a reset password email. You can send a reset password email with the customerRecover mutation.
mutation customerResetByUrl($resetUrl: URL!, $password: String!) {
  customerResetByUrl(resetUrl: $resetUrl, password: $password) {
    customer {
      id
      email
      firstName
      lastName
      phone
      acceptsMarketing
    }
    customerAccessToken {
      accessToken
      expiresAt
    }
    customerUserErrors {
      code
      field
      message
    }
  }
}
