import type { Metadata } from "next";
import "@workspace/ui/styles/globals.css";
import "@/styles/website.styles.css";
import { FuturaLTPro, WalbaumPro } from "@/lib/fonts";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "SENZ8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${FuturaLTPro.variable} ${WalbaumPro.variable} font-sans antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
