import type { Metadata } from "next";
import "@workspace/ui/styles/globals.css";
import "@/styles/website.styles.css";
import Navbar from "../components/ui/navbar";
import PublicPageFooter from "../components/ui/footer";
import { FuturaLTProBook, FuturaLTProLight, WalbaumPro } from "@/lib/fonts";
import CartSheet from "@/components/shared/cart-sheet";
import { Toaster } from "@workspace/ui/components/sonner";
import { SessionProvider } from "@/components/providers/session.provider";

export const metadata: Metadata = {
  title: "SENZ8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <SmoothScrollProvider /> */}
      <body
        className={`${FuturaLTProBook.variable} ${WalbaumPro.variable} ${FuturaLTProLight.variable} font-sans antialiased`}
      >
        <SessionProvider>
          <Toaster />
          <Navbar />
          {children}
          <PublicPageFooter />
          <CartSheet />
        </SessionProvider>
      </body>
    </html>
  );
}
