import type { Metadata } from "next";
import "@workspace/ui/styles/globals.css";
import "@/styles/website.styles.css";
import Navbar from "../components/ui/navbar";
import PublicPageFooter from "../components/ui/footer";
import { FuturaLTPro, WalbaumPro } from "@/lib/fonts";
import CartSheet from "@/components/shared/cart-sheet";
import { Toaster } from "@workspace/ui/components/sonner";
import { SessionProvider } from "@/components/providers/session.provider";
import ReactQueryProvider from "@/components/providers/react-query.provider";

export const metadata: Metadata = {
  title: "SENZ8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <SmoothScrollProvider /> */}
      <body
        className={`${FuturaLTPro.variable} ${WalbaumPro.variable} font-sans antialiased`}
      >
        <ReactQueryProvider>
          <SessionProvider>
            <Toaster />
            <Navbar />
            {children}
            <PublicPageFooter />
            <CartSheet />
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
